---
layout: cv
title: Benjamin Young's CV
---
# Benjamin L. Young
234.755.1190

<div id="webaddress">
<a href="blyoung4960@gmail.com">blyoung4960@gmail.com</a>
| <a href="linkedin.com/in/blyoung4960">My LinkedIn</a>
</div>


## Education

Brigham Young University - Idaho                                                                            Rexburg, ID
Bachelor of Science in Data Science                                                         August 2021 - December 2025
• Related Courses: Business Law, Spreadsheet Analysis, Financial Accounting, Small Business Management, Public Speaking,Business Fundamentals, Advanced Writing and Reasoning

Aurora High School Aurora, OH
High School Diploma Graduation: April 2019

## Work Experience

Broulim's Fresh Foods Supermarket       Rexburg, ID
Cashier                                 January 2022 - Present
• Sustained a perfectly balanced till more than 80% of shifts by managing cash and receipts gathered, to ensure effective bookkeeping
• Communicated with more than 150 customers of various ages, nationalities, and languages, by asking questions and answering concerns, 
increasing receptiveness and customer retention

Ganley Chrysler of Aurora               Aurora, OH
Porter / Car Detailer                   March 2018 - August 2022
• Cleaned, detailed, and arranged car inventory ranging from 60 to 200 cars
• Coordinated with sales representatives, general managers, and service technicians ten or more times per day
• Determined solutions when given assignments from three or more managers to be completed by deadlines
• Demonstrated independence in detailing and maintaining inventory, reducing the need for additional employees

Small Business Management - Bus 200      Rexburg, ID
Student Consultant (Research Business and Development Center) November 2021 - December 2021
• Collaborated in-person and digitally with owner and three teammates to analyze weaknesses in the business
• Offered constructive feedback to developing business, Mom MBA, totaling around 40 hours of work during four weeks
• Created, ran, and monitored one digital advertisement across multiple social networks reaching 729 potential leads and gaining 16 emails 
from clients of interest
• Surveyed dozens of third party friends to gather constructive criticism for the business's website
• Collected all data into three easy-to-operate folders for the client's convenience

American Eagle Outfitters Inc              Aurora, OH
Sales Associate                             July 2019 - August 2019
• Responded to dozens of customer questions and needs each day
• Suggested products and sizes for customers, meeting daily and weekly quotas

Porsche of Beachwood                        Beachwood, OH
Porter / Car Detailer (Unpaid Three Week Internship) March 2019 - March 2019
• Observed firsthand how a car dealership is operated and maintained for three weeks
• Cleaned, detailed, and organized car inventory of at most 60 cars
• Learned all detailing methods and porter duties within three weeks by questioning coworkers

## Volenteer Experience

Full-time Volunteer Representative          Baton Rouge, LA
The Church of Jesus Christ of Latter-day Saints August 2019 - July 2021
• Served in Abidjan, Côte d'Ivoire, West Africa for eight months and Baton Rouge, LA for fourteen months
• Developed personal plans for hundreds of individuals to assist in achievement of proactive goals
• Prepared and taught weekly training meetings for fellow volunteers to increase effectiveness
• Obtained fluency in French within seven months of living in Africa
• Adapted to two entirely different cultures and connected with the local people through strong interpersonal skills
• Adjusted to fluctuating assignments and locations during the Covid-19 pandemic
• Managed volunteer groups up to thirty individuals for a year by collecting reports and counseling

Boy Scouts of America                       Hiram, OH
Eagle Scout Rank                            December 2008 - December 2018
• Led and supported at least twelve other scout, through personal example
• Honored and lived an established code of conduct, even in the five or more years since leaving the organization
• Organized, planned, and conducted an independent project in 2017 to restore the condition of Nelson Ledges State Park in two weeks

<!-- ### Footer

Last updated: Apr 2024 -->